I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_amity.rpy", line 15, in script
    call screen hallway
ScriptError: could not find label 'sexroom'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Alienware\Downloads\renpy-6.99.11-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Alienware\Downloads\renpy-6.99.11-sdk\renpy\main.py", line 478, in main
    run(restart)
  File "C:\Users\Alienware\Downloads\renpy-6.99.11-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\Alienware\Downloads\renpy-6.99.11-sdk\renpy\execution.py", line 734, in run_context
    context.run()
  File "game/script_amity.rpy", line 15, in script
    call screen hallway
  File "C:\Users\Alienware\Downloads\renpy-6.99.11-sdk\renpy\script.py", line 843, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'sexroom'.

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Point and Click Test 0.0
