I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/000statements.rpy", line 458, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen mysteryImage is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "lib/windows-i686/script.rpyc", line 186, in script
  File "C:\Users\idowo\Downloads\renpy-6.99.11-sdk\renpy\ast.py", line 1696, in execute
    self.call("execute")
  File "C:\Users\idowo\Downloads\renpy-6.99.11-sdk\renpy\ast.py", line 1714, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\idowo\Downloads\renpy-6.99.11-sdk\renpy\statements.py", line 144, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 458, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\idowo\Downloads\renpy-6.99.11-sdk\renpy\display\screen.py", line 997, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen mysteryImage is not known.


Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Point and Click Test 0.0
